Added the new stencil type as suggested by Rupert.
stfc/dl_esm_inf pull request #11
Opened 2018-11-08 23:33 UTC by hiker

Fixed #9.

2018-11-12 09:57 UTC, arporter requested changes
Looks good and I would have merged it but for the fact I don't understand the use of `GO_READ` as a kind parameter? If a kind parameter is needed there (and it might not be) then we will have to define a new one - see in-line comment.
New code compiles OK with gfortran and PGI. I would have tried Intel but seem to have issues with our license server at the mo.

2018-11-12 09:57 UTC, arporter commented on finite_difference/src/argument_mod.f90
> +  integer(kind(GO_READ)) :: arg_intent
I don't think we should use `GO_READ` as a kind parameter. If a kind is needed here then we should add a suitable parameter to kind_params_mod.f90 and use that instead.

2018-11-12 09:57 UTC, arporter commented on finite_difference/src/argument_mod.f90
> +type :: go_stencil
Please could you update the copyright notice on this file.

2018-11-12 11:27 UTC, hiker commented on finite_difference/src/argument_mod.f90
> +  integer(kind(GO_READ)) :: arg_intent
I can't comment on this, I admit I blindly copied @rupertford 's code :) Am happy to remove the kind.

2018-11-12 11:28 UTC, hiker commented on finite_difference/src/argument_mod.f90
> +type :: go_stencil
Done, and I didn't add myself on purpose, since I only added Rupert's code.

2018-11-13 12:27 UTC, hiker commented on finite_difference/src/argument_mod.f90
> +  integer(kind(GO_READ)) :: arg_intent
OK, considering that this line is not at all related to the issue handled here, I just reverted that part of the patch, and only left the stencil type change in.

@rupertford if you want a kind type, best open a new issue for that.

2018-11-13 12:27 UTC, hiker commented
Ready for another review.

2018-11-13 16:13 UTC, arporter approved these changes
All looks good. `make test` is successful.
Thanks for doing this.

2018-11-13 16:13 UTC, merged